### ISSUE TITLE
Utilisation et destruction des items frames

### ISSUE THREAD

**Issue by Chemiman** [Tabinol/secuboid-minecraft-plugin#29]
Créer une permission qui permet d'autoriser ou non la rotation d'un item contenu dans un item.
Créer une permission qui permet d'autoriser ou non le dépôt et la récupération d'un item dans l'item frame.
Créer une permission qui permet d'autoriser ou non la destruction d'un item frame avec un tir de flèche.

**Comment by Breston8** [comment]
Au passage, la mécanique des flèches peut se reproduire avec un bateau:
monter dedans et foncer dans un item frame fera loot l'item frame et l'entité qu'il contient.
